- name: Recibir y extraer el tarball
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Guardar el tarball en un archivo temporal
      copy:
        content: "{{ tarball_base64 | b64decode }}"
        dest: "/tmp/awx_received.tar.gz"
        mode: '0644'

    - name: Crear el directorio de destino si no existe
      file:
        path: /tmp/awx_extracted
        state: directory
        mode: '0755'

    - name: Extraer el archivo tar.gz
      unarchive:
        src: "/tmp/awx_received.tar.gz"
        dest: "/tmp/awx_extracted"
        remote_src: yes

    - name: Mostrar los archivos extraídos
      command: ls -lR /tmp/awx_extracted
      register: extracted_files


    - name: Mostrar los archivos extraídos
      debug:
        msg: "{{ extracted_files.stdout_lines }}"
