- name: Crear y empaquetar archivos en un tarball
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Crear un directorio temporal con archivos
      file:
        path: /tmp/awx_shared_dir
        state: directory

    - name: Crear archivos de ejemplo
      copy:
        content: "Este es un archivo de prueba"
        dest: "/tmp/awx_shared_dir/archivo{{ item }}.txt"
      loop: [1, 2, 3]

    - name: Comprimir el directorio en un tar.gz
      archive:
        path: /tmp/awx_shared_dir
        dest: /tmp/awx_shared_dir.tar.gz  # Se agrega explícitamente el destino
        format: gz
      register: tar_result


    - name: Leer el contenido del archivo tar.gz
      slurp:
        src: "{{ tar_result.dest }}"
      register: tarball_data

    - name: Pasar el contenido del tarball al siguiente job
      set_stats:
        data:
          tarball_base64: "{{ tarball_data['content'] }}"
